// Built-in default libraries shared by DietBuilder (foods, habits), Week4 (cardio) and the
// admin Library tab (Week6). Admins can hide any built-in for their company via the
// company_hidden_items table (kind: 'food' | 'habit' | 'cardio', matched by name).
export const MASTER_HABITS = [
  {id:'supps',   name:'Take supplements',             defaultTarget:7},
  {id:'lemon',   name:'20oz Lemon Water upon waking', defaultTarget:7},
  {id:'water',   name:'1 Gallon Water Daily',         defaultTarget:7},
  {id:'steps',   name:'Daily Step Goal Hit',          defaultTarget:7},
  {id:'wake5',   name:'Wake up at 5 AM',              defaultTarget:7},
  {id:'wake530', name:'Wake up at 5:30 AM',           defaultTarget:7},
  {id:'wake6',   name:'Wake up at 6 AM',              defaultTarget:7},
  {id:'workout', name:'Workout',                      defaultTarget:5},
  {id:'cold',    name:'Cold Shower / Ice Bath',       defaultTarget:7},
  {id:'sleep8',  name:'8 Hour Sleep Window',          defaultTarget:7},
  {id:'read',    name:'Read 30 Minutes',              defaultTarget:7},
  {id:'meditate',name:'Meditate',                     defaultTarget:7},
  {id:'journal', name:'Journal / Prayer',             defaultTarget:7},
  {id:'cardio',  name:'45-60 Min Walk / Cardio',      defaultTarget:5},
  {id:'fast12',  name:'12 Hour No Eating Window',     defaultTarget:7},
  {id:'fast16',  name:'16 Hour No Eating Window',     defaultTarget:5},
  {id:'prep',    name:'Meal Prep Done',               defaultTarget:1},
  {id:'nophone', name:'No Phone First Hour of Day',   defaultTarget:7},
]

export const FOODS = [
  {name:'Organic Chicken Breast',serving:'4oz',cal:120,pro:21,fat:4,carb:0,fib:0,cat:'Proteins'},
  {name:'Wild Caught Salmon',serving:'4oz',cal:237,pro:28.7,fat:13.6,carb:0,fib:0,cat:'Proteins'},
  {name:'Top Sirloin',serving:'4oz',cal:187,pro:34.7,fat:6,carb:0,fib:0,cat:'Proteins'},
  {name:'99% Lean Ground Turkey',serving:'4oz',cal:120,pro:28,fat:1,carb:0,fib:0,cat:'Proteins'},
  {name:'Wild Caught Shrimp',serving:'4oz',cal:112,pro:26.7,fat:0.7,carb:0,fib:0,cat:'Proteins'},
  {name:'Mahi Mahi',serving:'4oz',cal:124,pro:26.7,fat:1.3,carb:0,fib:0,cat:'Proteins'},
  {name:'Organic Egg Whites',serving:'184g',cal:80,pro:18,fat:0,carb:0,fib:0,cat:'Proteins'},
  {name:'Whole Omega-3 Egg',serving:'1 egg',cal:90,pro:8.6,fat:6.1,carb:0,fib:0,cat:'Proteins'},
  {name:'Filet Mignon',serving:'4oz',cal:227,pro:34.7,fat:9.3,carb:0,fib:0,cat:'Proteins'},
  {name:'Grass-Fed Ground Beef 96/4',serving:'4oz',cal:170,pro:24,fat:8,carb:0,fib:0,cat:'Proteins'},
  {name:'Medipure Protein',serving:'1 scoop',cal:120,pro:22,fat:2,carb:5,fib:1,cat:'Proteins'},
  {name:'Wild Caught Tuna (drained)',serving:'4oz',cal:124,pro:28.2,fat:1.1,carb:0,fib:0,cat:'Proteins'},
  {name:'Brown Rice (cooked)',serving:'195g',cal:218,pro:4.5,fat:1.6,carb:45,fib:3.5,cat:'Carbohydrates'},
  {name:'White Rice (cooked)',serving:'186g',cal:242,pro:4.4,fat:0.4,carb:53,fib:0.6,cat:'Carbohydrates'},
  {name:'Oatmeal (dry)',serving:'40g',cal:150,pro:5,fat:3,carb:27,fib:4,cat:'Carbohydrates'},
  {name:'Red Potato',serving:'148g',cal:150,pro:3,fat:0,carb:26,fib:3,cat:'Carbohydrates'},
  {name:'Sweet Potato',serving:'130g',cal:112,pro:2,fat:0,carb:26,fib:4,cat:'Carbohydrates'},
  {name:'Quinoa (cooked)',serving:'185g',cal:222,pro:8,fat:3.6,carb:39,fib:5.2,cat:'Carbohydrates'},
  {name:'Ezekiel Bread',serving:'1 slice',cal:80,pro:5,fat:0.5,carb:15,fib:3,cat:'Carbohydrates'},
  {name:'Cream of Rice (dry)',serving:'45g',cal:150,pro:2,fat:0,carb:35,fib:0.3,cat:'Carbohydrates'},
  {name:'Lentil Pasta (dry)',serving:'56g',cal:200,pro:15,fat:1.5,carb:34,fib:3,cat:'Carbohydrates'},
  {name:'Extra Virgin Olive Oil',serving:'14g',cal:120,pro:0,fat:14,carb:0,fib:0,cat:'Fats'},
  {name:'Coconut Oil (unrefined)',serving:'14g',cal:120,pro:0,fat:14,carb:0,fib:0,cat:'Fats'},
  {name:'Avocado',serving:'50g',cal:80,pro:1,fat:7.3,carb:4.3,fib:3.4,cat:'Fats'},
  {name:'Almond Butter',serving:'32g',cal:192,pro:6.8,fat:17.4,carb:6.1,fib:3.4,cat:'Fats'},
  {name:'Almonds',serving:'28g',cal:164,pro:6,fat:14.2,carb:6.1,fib:3.5,cat:'Fats'},
  {name:'Chia Seeds',serving:'12g',cal:58,pro:2,fat:3.7,carb:5,fib:4.1,cat:'Fats'},
  {name:'Raw Honey',serving:'7g',cal:20,pro:0,fat:0,carb:6,fib:0,cat:'Fats'},
  {name:'Blueberries',serving:'100g',cal:68,pro:0.7,fat:0.3,carb:14.5,fib:2.4,cat:'Fruits/Vegetables'},
  {name:'Mixed Berries (frozen)',serving:'100g',cal:55,pro:0.8,fat:0.3,carb:12,fib:2.5,cat:'Fruits/Vegetables'},
  {name:'Strawberries',serving:'100g',cal:30,pro:0.8,fat:0.1,carb:6,fib:2,cat:'Fruits/Vegetables'},
  {name:'Banana',serving:'100g',cal:103,pro:1.2,fat:0.3,carb:23.2,fib:2.6,cat:'Fruits/Vegetables'},
  {name:'Broccoli',serving:'100g',cal:38,pro:4.4,fat:0.9,carb:1.8,fib:2.6,cat:'Fruits/Vegetables'},
  {name:'Green Beans (canned)',serving:'100g',cal:21,pro:1,fat:0.4,carb:4.1,fib:1.5,cat:'Fruits/Vegetables'},
  {name:'Baby Spinach',serving:'100g',cal:29,pro:2.8,fat:0.8,carb:1.6,fib:1.5,cat:'Fruits/Vegetables'},
  {name:'Asparagus',serving:'100g',cal:29,pro:2.9,fat:0.6,carb:2,fib:2.1,cat:'Fruits/Vegetables'},
  {name:'Cucumber',serving:'80g',cal:12,pro:0.5,fat:0.1,carb:2.2,fib:0.6,cat:'Fruits/Vegetables'},
  {name:'Fish Oil 2000mg',serving:'2 caps',cal:20,pro:0,fat:2,carb:0,fib:0,cat:'Supplements'},
  {name:'Glutamine 20g',serving:'20g',cal:0,pro:0,fat:0,carb:0,fib:0,cat:'Supplements'},
  {name:'Bloat Eaze',serving:'1 scoop',cal:10,pro:0,fat:0,carb:2,fib:0,cat:'Supplements'},
  {name:'Magnesium',serving:'1 scoop',cal:5,pro:0,fat:0,carb:1,fib:0,cat:'Supplements'},
  {name:'Water (16oz)',serving:'16oz',cal:0,pro:0,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
  {name:'Black Coffee',serving:'240ml',cal:5,pro:0.3,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
  {name:'Matcha Green Tea',serving:'240ml',cal:5,pro:0.5,fat:0,carb:1,fib:0,cat:'Drinks/Condiments'},
  {name:'Green Tea',serving:'240ml',cal:2,pro:0,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
  {name:'Organic Apple Juice',serving:'250ml',cal:115,pro:0.2,fat:0.3,carb:28,fib:0.5,cat:'Drinks/Condiments'},
  {name:'Aloe Vera Juice',serving:'59ml',cal:4,pro:0,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
  {name:'Beef Bone Broth',serving:'150ml',cal:25,pro:5,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
  {name:'Yellow Mustard',serving:'5g',cal:3,pro:0.2,fat:0.1,carb:0.3,fib:0.1,cat:'Drinks/Condiments'},
  {name:'Hot Sauce',serving:'5g',cal:0,pro:0,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
  {name:'Salsa',serving:'30g',cal:10,pro:0.4,fat:0,carb:2,fib:0.5,cat:'Drinks/Condiments'},
  {name:'Himalayan Sea Salt',serving:'1g',cal:0,pro:0,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
  {name:'Iodized Sea Salt',serving:'1g',cal:0,pro:0,fat:0,carb:0,fib:0,cat:'Drinks/Condiments'},
]

export const CARDIO_TYPES = [
  'Treadmill','Bike','HIIT','Stairmaster','Brisk Walk','Run',
  'Swimming','Rowing Machine','Jump Rope','Elliptical',
]
// Eden's default "Helpful Resources & Lab Links" — shown to any org that hasn't
// customized its own list yet (company_resource_links), and used to seed new orgs.
export const DEFAULT_RESOURCE_LINKS = [
  ['Male Blood Work Panel',  'https://shop.advancedvitalityhrt.com/?ref=LIFESTYLEOFEDEN',''],
  ['Female Blood Work Panel','https://shop.advancedvitalityhrt.com/?ref=LIFESTYLEOFEDEN',''],
  ['DUTCH Test',             'https://www.practitionerdepot.com/products/dutch-test','Code: TOGNIETTI10'],
  ['GI Map',                 'https://www.practitionerdepot.com/products/gi-map','Code: TOGNIETTI10'],
  ['Book a Call',            'https://links.lifestyleofeden.com/widget/booking/2kKUGzYZqAaNBVpd5uzA',''],
  ['NuEthix Supplements',    'https://nuethix.com','Code: TOGNIETTI10'],
]
