import { Router, type IRouter } from "express";
import healthRouter from "./health";
import recipeDetailsRouter from "./recipeDetails";
import ghlIntakeRouter from "./ghlIntake";
import authRouter from "./auth";
import bulkImportRouter from "./bulkImport";
import checkinFormRouter from "./checkinForm";
import huddleRouter from "./huddle";
import profileAuditRouter from "./profileAudit";
import welcomeRouter from "./welcome";
import teamUploadRouter from "./teamUpload";
import auditLoginRouter from "./auditLogin";
import canvasRouter from "./canvas";
import invitesRouter from "./invites";
import broadcastsRouter from "./broadcasts";
import dbaRouter from "./dba";
import ouraRouter from "./oura";
import metaAdsRouter from "./metaAds";

const router: IRouter = Router();

router.use(healthRouter);
router.use(recipeDetailsRouter);
router.use(ghlIntakeRouter);
router.use(authRouter);
router.use(bulkImportRouter);
router.use(checkinFormRouter);
router.use(huddleRouter);
router.use(profileAuditRouter);
router.use(welcomeRouter);
router.use(teamUploadRouter);
router.use(auditLoginRouter);
router.use(canvasRouter);
router.use(invitesRouter);
router.use(broadcastsRouter);
router.use(dbaRouter);
router.use(ouraRouter);
router.use(metaAdsRouter);

export default router;
