import { Router, type IRouter } from "express";
import healthRouter from "./health";
import recipeDetailsRouter from "./recipeDetails";
import ghlIntakeRouter from "./ghlIntake";
import communityPostRouter from "./communityPost";
import authRouter from "./auth";
import bulkImportRouter from "./bulkImport";
import checkinFormRouter from "./checkinForm";
import huddleRouter from "./huddle";
import profileAuditRouter from "./profileAudit";
import welcomeRouter from "./welcome";
import teamUploadRouter from "./teamUpload";
import orgLogoRouter from "./orgLogo";
import auditLoginRouter from "./auditLogin";
import canvasRouter from "./canvas";
import invitesRouter from "./invites";
import broadcastsRouter from "./broadcasts";
import dbaRouter from "./dba";
import ouraRouter from "./oura";
import metaAdsRouter from "./metaAds";
import ghlKpiRouter from "./ghlKpi";
import pushRouter from "./push";
import reactionsRouter from "./reactions";
import teamSeenRouter from "./teamSeen";
import msgUnreadRouter from "./msgUnread";
import teamMessagesRouter from "./teamMessages";

const router: IRouter = Router();

router.use(healthRouter);
router.use(recipeDetailsRouter);
router.use(ghlIntakeRouter);
router.use(communityPostRouter);
router.use(authRouter);
router.use(bulkImportRouter);
router.use(checkinFormRouter);
router.use(huddleRouter);
router.use(profileAuditRouter);
router.use(welcomeRouter);
router.use(teamUploadRouter);
router.use(orgLogoRouter);
router.use(auditLoginRouter);
router.use(canvasRouter);
router.use(invitesRouter);
router.use(broadcastsRouter);
router.use(dbaRouter);
router.use(ouraRouter);
router.use(metaAdsRouter);
router.use(ghlKpiRouter);
router.use(pushRouter);
router.use(reactionsRouter);
router.use(teamSeenRouter);
router.use(msgUnreadRouter);
router.use(teamMessagesRouter);

export default router;
